#include "config.h"
#include "types.h"

#include "constants/item.h"
#include "constants/species.h"

#include "roamer.h"
#include "save.h"
#include "wild_encounter_randomizer.h"

// Every base species valid as a wild-encounter randomizer target: the full national dex
// (SPECIES_1 .. SPECIES_PECHARUNT / SPECIES_MAX_MON_NUM at the time this was generated),
// excluding SPECIES_NONE and SPECIES_EGG. Mega evolutions, regional forms, gigantamax forms
// and cosmetic-only forms (Rotom appliances, Arceus plates, etc.) are intentionally left out:
// none of them are used by the vanilla wild encounter tables either, and several of them are
// not safe to hand out as a normal standalone wild Pokemon.
//
// Also intentionally left out: SPECIES_BAD_EGG and the unused/reserved SPECIES_496..SPECIES_543
// slots. These have no real data (name "-----", no sprite) - see data/Species.c - so they must
// never be handed out here. This same pool backs the trainer randomizer below too
// (TrainerRandomizer_GetReplacementSpecies), so removing them here fixes both wild encounters
// and NPC trainer parties at once.
//
// Regenerate this list with tools/randomize_wild_encounters.py's species-pool logic (or by
// hand from include/constants/species.h) if you add fakemons and want them in the pool too -
// make sure to re-exclude any nameless/spriteless reserved slots if you do.
static const u16 sWildRandomizerSpeciesPool[] = {
    SPECIES_BULBASAUR, SPECIES_IVYSAUR, SPECIES_VENUSAUR, SPECIES_CHARMANDER, SPECIES_CHARMELEON, SPECIES_CHARIZARD,
    SPECIES_SQUIRTLE, SPECIES_WARTORTLE, SPECIES_BLASTOISE, SPECIES_CATERPIE, SPECIES_METAPOD, SPECIES_BUTTERFREE,
    SPECIES_WEEDLE, SPECIES_KAKUNA, SPECIES_BEEDRILL, SPECIES_PIDGEY, SPECIES_PIDGEOTTO, SPECIES_PIDGEOT,
    SPECIES_RATTATA, SPECIES_RATICATE, SPECIES_SPEAROW, SPECIES_FEAROW, SPECIES_EKANS, SPECIES_ARBOK,
    SPECIES_PIKACHU, SPECIES_RAICHU, SPECIES_SANDSHREW, SPECIES_SANDSLASH, SPECIES_NIDORAN_F, SPECIES_NIDORINA,
    SPECIES_NIDOQUEEN, SPECIES_NIDORAN_M, SPECIES_NIDORINO, SPECIES_NIDOKING, SPECIES_CLEFAIRY, SPECIES_CLEFABLE,
    SPECIES_VULPIX, SPECIES_NINETALES, SPECIES_JIGGLYPUFF, SPECIES_WIGGLYTUFF, SPECIES_ZUBAT, SPECIES_GOLBAT,
    SPECIES_ODDISH, SPECIES_GLOOM, SPECIES_VILEPLUME, SPECIES_PARAS, SPECIES_PARASECT, SPECIES_VENONAT,
    SPECIES_VENOMOTH, SPECIES_DIGLETT, SPECIES_DUGTRIO, SPECIES_MEOWTH, SPECIES_PERSIAN, SPECIES_PSYDUCK,
    SPECIES_GOLDUCK, SPECIES_MANKEY, SPECIES_PRIMEAPE, SPECIES_GROWLITHE, SPECIES_ARCANINE, SPECIES_POLIWAG,
    SPECIES_POLIWHIRL, SPECIES_POLIWRATH, SPECIES_ABRA, SPECIES_KADABRA, SPECIES_ALAKAZAM, SPECIES_MACHOP,
    SPECIES_MACHOKE, SPECIES_MACHAMP, SPECIES_BELLSPROUT, SPECIES_WEEPINBELL, SPECIES_VICTREEBEL, SPECIES_TENTACOOL,
    SPECIES_TENTACRUEL, SPECIES_GEODUDE, SPECIES_GRAVELER, SPECIES_GOLEM, SPECIES_PONYTA, SPECIES_RAPIDASH,
    SPECIES_SLOWPOKE, SPECIES_SLOWBRO, SPECIES_MAGNEMITE, SPECIES_MAGNETON, SPECIES_FARFETCHD, SPECIES_DODUO,
    SPECIES_DODRIO, SPECIES_SEEL, SPECIES_DEWGONG, SPECIES_GRIMER, SPECIES_MUK, SPECIES_SHELLDER,
    SPECIES_CLOYSTER, SPECIES_GASTLY, SPECIES_HAUNTER, SPECIES_GENGAR, SPECIES_ONIX, SPECIES_DROWZEE,
    SPECIES_HYPNO, SPECIES_KRABBY, SPECIES_KINGLER, SPECIES_VOLTORB, SPECIES_ELECTRODE, SPECIES_EXEGGCUTE,
    SPECIES_EXEGGUTOR, SPECIES_CUBONE, SPECIES_MAROWAK, SPECIES_HITMONLEE, SPECIES_HITMONCHAN, SPECIES_LICKITUNG,
    SPECIES_KOFFING, SPECIES_WEEZING, SPECIES_RHYHORN, SPECIES_RHYDON, SPECIES_CHANSEY, SPECIES_TANGELA,
    SPECIES_KANGASKHAN, SPECIES_HORSEA, SPECIES_SEADRA, SPECIES_GOLDEEN, SPECIES_SEAKING, SPECIES_STARYU,
    SPECIES_STARMIE, SPECIES_MR_MIME, SPECIES_SCYTHER, SPECIES_JYNX, SPECIES_ELECTABUZZ, SPECIES_MAGMAR,
    SPECIES_PINSIR, SPECIES_TAUROS, SPECIES_MAGIKARP, SPECIES_GYARADOS, SPECIES_LAPRAS, SPECIES_DITTO,
    SPECIES_EEVEE, SPECIES_VAPOREON, SPECIES_JOLTEON, SPECIES_FLAREON, SPECIES_PORYGON, SPECIES_OMANYTE,
    SPECIES_OMASTAR, SPECIES_KABUTO, SPECIES_KABUTOPS, SPECIES_AERODACTYL, SPECIES_SNORLAX, SPECIES_ARTICUNO,
    SPECIES_ZAPDOS, SPECIES_MOLTRES, SPECIES_DRATINI, SPECIES_DRAGONAIR, SPECIES_DRAGONITE, SPECIES_MEWTWO,
    SPECIES_MEW, SPECIES_CHIKORITA, SPECIES_BAYLEEF, SPECIES_MEGANIUM, SPECIES_CYNDAQUIL, SPECIES_QUILAVA,
    SPECIES_TYPHLOSION, SPECIES_TOTODILE, SPECIES_CROCONAW, SPECIES_FERALIGATR, SPECIES_SENTRET, SPECIES_FURRET,
    SPECIES_HOOTHOOT, SPECIES_NOCTOWL, SPECIES_LEDYBA, SPECIES_LEDIAN, SPECIES_SPINARAK, SPECIES_ARIADOS,
    SPECIES_CROBAT, SPECIES_CHINCHOU, SPECIES_LANTURN, SPECIES_PICHU, SPECIES_CLEFFA, SPECIES_IGGLYBUFF,
    SPECIES_TOGEPI, SPECIES_TOGETIC, SPECIES_NATU, SPECIES_XATU, SPECIES_MAREEP, SPECIES_FLAAFFY,
    SPECIES_AMPHAROS, SPECIES_BELLOSSOM, SPECIES_MARILL, SPECIES_AZUMARILL, SPECIES_SUDOWOODO, SPECIES_POLITOED,
    SPECIES_HOPPIP, SPECIES_SKIPLOOM, SPECIES_JUMPLUFF, SPECIES_AIPOM, SPECIES_SUNKERN, SPECIES_SUNFLORA,
    SPECIES_YANMA, SPECIES_WOOPER, SPECIES_QUAGSIRE, SPECIES_ESPEON, SPECIES_UMBREON, SPECIES_MURKROW,
    SPECIES_SLOWKING, SPECIES_MISDREAVUS, SPECIES_UNOWN, SPECIES_WOBBUFFET, SPECIES_GIRAFARIG, SPECIES_PINECO,
    SPECIES_FORRETRESS, SPECIES_DUNSPARCE, SPECIES_GLIGAR, SPECIES_STEELIX, SPECIES_SNUBBULL, SPECIES_GRANBULL,
    SPECIES_QWILFISH, SPECIES_SCIZOR, SPECIES_SHUCKLE, SPECIES_HERACROSS, SPECIES_SNEASEL, SPECIES_TEDDIURSA,
    SPECIES_URSARING, SPECIES_SLUGMA, SPECIES_MAGCARGO, SPECIES_SWINUB, SPECIES_PILOSWINE, SPECIES_CORSOLA,
    SPECIES_REMORAID, SPECIES_OCTILLERY, SPECIES_DELIBIRD, SPECIES_MANTINE, SPECIES_SKARMORY, SPECIES_HOUNDOUR,
    SPECIES_HOUNDOOM, SPECIES_KINGDRA, SPECIES_PHANPY, SPECIES_DONPHAN, SPECIES_PORYGON2, SPECIES_STANTLER,
    SPECIES_SMEARGLE, SPECIES_TYROGUE, SPECIES_HITMONTOP, SPECIES_SMOOCHUM, SPECIES_ELEKID, SPECIES_MAGBY,
    SPECIES_MILTANK, SPECIES_BLISSEY, SPECIES_RAIKOU, SPECIES_ENTEI, SPECIES_SUICUNE, SPECIES_LARVITAR,
    SPECIES_PUPITAR, SPECIES_TYRANITAR, SPECIES_LUGIA, SPECIES_HO_OH, SPECIES_CELEBI, SPECIES_TREECKO,
    SPECIES_GROVYLE, SPECIES_SCEPTILE, SPECIES_TORCHIC, SPECIES_COMBUSKEN, SPECIES_BLAZIKEN, SPECIES_MUDKIP,
    SPECIES_MARSHTOMP, SPECIES_SWAMPERT, SPECIES_POOCHYENA, SPECIES_MIGHTYENA, SPECIES_ZIGZAGOON, SPECIES_LINOONE,
    SPECIES_WURMPLE, SPECIES_SILCOON, SPECIES_BEAUTIFLY, SPECIES_CASCOON, SPECIES_DUSTOX, SPECIES_LOTAD,
    SPECIES_LOMBRE, SPECIES_LUDICOLO, SPECIES_SEEDOT, SPECIES_NUZLEAF, SPECIES_SHIFTRY, SPECIES_TAILLOW,
    SPECIES_SWELLOW, SPECIES_WINGULL, SPECIES_PELIPPER, SPECIES_RALTS, SPECIES_KIRLIA, SPECIES_GARDEVOIR,
    SPECIES_SURSKIT, SPECIES_MASQUERAIN, SPECIES_SHROOMISH, SPECIES_BRELOOM, SPECIES_SLAKOTH, SPECIES_VIGOROTH,
    SPECIES_SLAKING, SPECIES_NINCADA, SPECIES_NINJASK, SPECIES_SHEDINJA, SPECIES_WHISMUR, SPECIES_LOUDRED,
    SPECIES_EXPLOUD, SPECIES_MAKUHITA, SPECIES_HARIYAMA, SPECIES_AZURILL, SPECIES_NOSEPASS, SPECIES_SKITTY,
    SPECIES_DELCATTY, SPECIES_SABLEYE, SPECIES_MAWILE, SPECIES_ARON, SPECIES_LAIRON, SPECIES_AGGRON,
    SPECIES_MEDITITE, SPECIES_MEDICHAM, SPECIES_ELECTRIKE, SPECIES_MANECTRIC, SPECIES_PLUSLE, SPECIES_MINUN,
    SPECIES_VOLBEAT, SPECIES_ILLUMISE, SPECIES_ROSELIA, SPECIES_GULPIN, SPECIES_SWALOT, SPECIES_CARVANHA,
    SPECIES_SHARPEDO, SPECIES_WAILMER, SPECIES_WAILORD, SPECIES_NUMEL, SPECIES_CAMERUPT, SPECIES_TORKOAL,
    SPECIES_SPOINK, SPECIES_GRUMPIG, SPECIES_SPINDA, SPECIES_TRAPINCH, SPECIES_VIBRAVA, SPECIES_FLYGON,
    SPECIES_CACNEA, SPECIES_CACTURNE, SPECIES_SWABLU, SPECIES_ALTARIA, SPECIES_ZANGOOSE, SPECIES_SEVIPER,
    SPECIES_LUNATONE, SPECIES_SOLROCK, SPECIES_BARBOACH, SPECIES_WHISCASH, SPECIES_CORPHISH, SPECIES_CRAWDAUNT,
    SPECIES_BALTOY, SPECIES_CLAYDOL, SPECIES_LILEEP, SPECIES_CRADILY, SPECIES_ANORITH, SPECIES_ARMALDO,
    SPECIES_FEEBAS, SPECIES_MILOTIC, SPECIES_CASTFORM, SPECIES_KECLEON, SPECIES_SHUPPET, SPECIES_BANETTE,
    SPECIES_DUSKULL, SPECIES_DUSCLOPS, SPECIES_TROPIUS, SPECIES_CHIMECHO, SPECIES_ABSOL, SPECIES_WYNAUT,
    SPECIES_SNORUNT, SPECIES_GLALIE, SPECIES_SPHEAL, SPECIES_SEALEO, SPECIES_WALREIN, SPECIES_CLAMPERL,
    SPECIES_HUNTAIL, SPECIES_GOREBYSS, SPECIES_RELICANTH, SPECIES_LUVDISC, SPECIES_BAGON, SPECIES_SHELGON,
    SPECIES_SALAMENCE, SPECIES_BELDUM, SPECIES_METANG, SPECIES_METAGROSS, SPECIES_REGIROCK, SPECIES_REGICE,
    SPECIES_REGISTEEL, SPECIES_LATIAS, SPECIES_LATIOS, SPECIES_KYOGRE, SPECIES_GROUDON, SPECIES_RAYQUAZA,
    SPECIES_JIRACHI, SPECIES_DEOXYS, SPECIES_TURTWIG, SPECIES_GROTLE, SPECIES_TORTERRA, SPECIES_CHIMCHAR,
    SPECIES_MONFERNO, SPECIES_INFERNAPE, SPECIES_PIPLUP, SPECIES_PRINPLUP, SPECIES_EMPOLEON, SPECIES_STARLY,
    SPECIES_STARAVIA, SPECIES_STARAPTOR, SPECIES_BIDOOF, SPECIES_BIBAREL, SPECIES_KRICKETOT, SPECIES_KRICKETUNE,
    SPECIES_SHINX, SPECIES_LUXIO, SPECIES_LUXRAY, SPECIES_BUDEW, SPECIES_ROSERADE, SPECIES_CRANIDOS,
    SPECIES_RAMPARDOS, SPECIES_SHIELDON, SPECIES_BASTIODON, SPECIES_BURMY, SPECIES_WORMADAM, SPECIES_MOTHIM,
    SPECIES_COMBEE, SPECIES_VESPIQUEN, SPECIES_PACHIRISU, SPECIES_BUIZEL, SPECIES_FLOATZEL, SPECIES_CHERUBI,
    SPECIES_CHERRIM, SPECIES_SHELLOS, SPECIES_GASTRODON, SPECIES_AMBIPOM, SPECIES_DRIFLOON, SPECIES_DRIFBLIM,
    SPECIES_BUNEARY, SPECIES_LOPUNNY, SPECIES_MISMAGIUS, SPECIES_HONCHKROW, SPECIES_GLAMEOW, SPECIES_PURUGLY,
    SPECIES_CHINGLING, SPECIES_STUNKY, SPECIES_SKUNTANK, SPECIES_BRONZOR, SPECIES_BRONZONG, SPECIES_BONSLY,
    SPECIES_MIME_JR, SPECIES_HAPPINY, SPECIES_CHATOT, SPECIES_SPIRITOMB, SPECIES_GIBLE, SPECIES_GABITE,
    SPECIES_GARCHOMP, SPECIES_MUNCHLAX, SPECIES_RIOLU, SPECIES_LUCARIO, SPECIES_HIPPOPOTAS, SPECIES_HIPPOWDON,
    SPECIES_SKORUPI, SPECIES_DRAPION, SPECIES_CROAGUNK, SPECIES_TOXICROAK, SPECIES_CARNIVINE, SPECIES_FINNEON,
    SPECIES_LUMINEON, SPECIES_MANTYKE, SPECIES_SNOVER, SPECIES_ABOMASNOW, SPECIES_WEAVILE, SPECIES_MAGNEZONE,
    SPECIES_LICKILICKY, SPECIES_RHYPERIOR, SPECIES_TANGROWTH, SPECIES_ELECTIVIRE, SPECIES_MAGMORTAR, SPECIES_TOGEKISS,
    SPECIES_YANMEGA, SPECIES_LEAFEON, SPECIES_GLACEON, SPECIES_GLISCOR, SPECIES_MAMOSWINE, SPECIES_PORYGON_Z,
    SPECIES_GALLADE, SPECIES_PROBOPASS, SPECIES_DUSKNOIR, SPECIES_FROSLASS, SPECIES_ROTOM, SPECIES_UXIE,
    SPECIES_MESPRIT, SPECIES_AZELF, SPECIES_DIALGA, SPECIES_PALKIA, SPECIES_HEATRAN, SPECIES_REGIGIGAS,
    SPECIES_GIRATINA, SPECIES_CRESSELIA, SPECIES_PHIONE, SPECIES_MANAPHY, SPECIES_DARKRAI, SPECIES_SHAYMIN,
    SPECIES_ARCEUS,
    SPECIES_VICTINI, SPECIES_SNIVY, SPECIES_SERVINE, SPECIES_SERPERIOR,
    SPECIES_TEPIG, SPECIES_PIGNITE, SPECIES_EMBOAR, SPECIES_OSHAWOTT, SPECIES_DEWOTT, SPECIES_SAMUROTT,
    SPECIES_PATRAT, SPECIES_WATCHOG, SPECIES_LILLIPUP, SPECIES_HERDIER, SPECIES_STOUTLAND, SPECIES_PURRLOIN,
    SPECIES_LIEPARD, SPECIES_PANSAGE, SPECIES_SIMISAGE, SPECIES_PANSEAR, SPECIES_SIMISEAR, SPECIES_PANPOUR,
    SPECIES_SIMIPOUR, SPECIES_MUNNA, SPECIES_MUSHARNA, SPECIES_PIDOVE, SPECIES_TRANQUILL, SPECIES_UNFEZANT,
    SPECIES_BLITZLE, SPECIES_ZEBSTRIKA, SPECIES_ROGGENROLA, SPECIES_BOLDORE, SPECIES_GIGALITH, SPECIES_WOOBAT,
    SPECIES_SWOOBAT, SPECIES_DRILBUR, SPECIES_EXCADRILL, SPECIES_AUDINO, SPECIES_TIMBURR, SPECIES_GURDURR,
    SPECIES_CONKELDURR, SPECIES_TYMPOLE, SPECIES_PALPITOAD, SPECIES_SEISMITOAD, SPECIES_THROH, SPECIES_SAWK,
    SPECIES_SEWADDLE, SPECIES_SWADLOON, SPECIES_LEAVANNY, SPECIES_VENIPEDE, SPECIES_WHIRLIPEDE, SPECIES_SCOLIPEDE,
    SPECIES_COTTONEE, SPECIES_WHIMSICOTT, SPECIES_PETILIL, SPECIES_LILLIGANT, SPECIES_BASCULIN, SPECIES_SANDILE,
    SPECIES_KROKOROK, SPECIES_KROOKODILE, SPECIES_DARUMAKA, SPECIES_DARMANITAN, SPECIES_MARACTUS, SPECIES_DWEBBLE,
    SPECIES_CRUSTLE, SPECIES_SCRAGGY, SPECIES_SCRAFTY, SPECIES_SIGILYPH, SPECIES_YAMASK, SPECIES_COFAGRIGUS,
    SPECIES_TIRTOUGA, SPECIES_CARRACOSTA, SPECIES_ARCHEN, SPECIES_ARCHEOPS, SPECIES_TRUBBISH, SPECIES_GARBODOR,
    SPECIES_ZORUA, SPECIES_ZOROARK, SPECIES_MINCCINO, SPECIES_CINCCINO, SPECIES_GOTHITA, SPECIES_GOTHORITA,
    SPECIES_GOTHITELLE, SPECIES_SOLOSIS, SPECIES_DUOSION, SPECIES_REUNICLUS, SPECIES_DUCKLETT, SPECIES_SWANNA,
    SPECIES_VANILLITE, SPECIES_VANILLISH, SPECIES_VANILLUXE, SPECIES_DEERLING, SPECIES_SAWSBUCK, SPECIES_EMOLGA,
    SPECIES_KARRABLAST, SPECIES_ESCAVALIER, SPECIES_FOONGUS, SPECIES_AMOONGUSS, SPECIES_FRILLISH, SPECIES_JELLICENT,
    SPECIES_ALOMOMOLA, SPECIES_JOLTIK, SPECIES_GALVANTULA, SPECIES_FERROSEED, SPECIES_FERROTHORN, SPECIES_KLINK,
    SPECIES_KLANG, SPECIES_KLINKLANG, SPECIES_TYNAMO, SPECIES_EELEKTRIK, SPECIES_EELEKTROSS, SPECIES_ELGYEM,
    SPECIES_BEHEEYEM, SPECIES_LITWICK, SPECIES_LAMPENT, SPECIES_CHANDELURE, SPECIES_AXEW, SPECIES_FRAXURE,
    SPECIES_HAXORUS, SPECIES_CUBCHOO, SPECIES_BEARTIC, SPECIES_CRYOGONAL, SPECIES_SHELMET, SPECIES_ACCELGOR,
    SPECIES_STUNFISK, SPECIES_MIENFOO, SPECIES_MIENSHAO, SPECIES_DRUDDIGON, SPECIES_GOLETT, SPECIES_GOLURK,
    SPECIES_PAWNIARD, SPECIES_BISHARP, SPECIES_BOUFFALANT, SPECIES_RUFFLET, SPECIES_BRAVIARY, SPECIES_VULLABY,
    SPECIES_MANDIBUZZ, SPECIES_HEATMOR, SPECIES_DURANT, SPECIES_DEINO, SPECIES_ZWEILOUS, SPECIES_HYDREIGON,
    SPECIES_LARVESTA, SPECIES_VOLCARONA, SPECIES_COBALION, SPECIES_TERRAKION, SPECIES_VIRIZION, SPECIES_TORNADUS,
    SPECIES_THUNDURUS, SPECIES_RESHIRAM, SPECIES_ZEKROM, SPECIES_LANDORUS, SPECIES_KYUREM, SPECIES_KELDEO,
    SPECIES_MELOETTA, SPECIES_GENESECT, SPECIES_CHESPIN, SPECIES_QUILLADIN, SPECIES_CHESNAUGHT, SPECIES_FENNEKIN,
    SPECIES_BRAIXEN, SPECIES_DELPHOX, SPECIES_FROAKIE, SPECIES_FROGADIER, SPECIES_GRENINJA, SPECIES_BUNNELBY,
    SPECIES_DIGGERSBY, SPECIES_FLETCHLING, SPECIES_FLETCHINDER, SPECIES_TALONFLAME, SPECIES_SCATTERBUG, SPECIES_SPEWPA,
    SPECIES_LITLEO, SPECIES_PYROAR, SPECIES_SKIDDO, SPECIES_GOGOAT, SPECIES_PANCHAM, SPECIES_PANGORO,
    SPECIES_FURFROU, SPECIES_ESPURR, SPECIES_MEOWSTIC, SPECIES_HONEDGE, SPECIES_DOUBLADE, SPECIES_AEGISLASH,
    SPECIES_SPRITZEE, SPECIES_AROMATISSE, SPECIES_SWIRLIX, SPECIES_SLURPUFF, SPECIES_INKAY, SPECIES_MALAMAR,
    SPECIES_BINACLE, SPECIES_BARBARACLE, SPECIES_SKRELP, SPECIES_DRAGALGE, SPECIES_CLAUNCHER, SPECIES_CLAWITZER,
    SPECIES_HELIOPTILE, SPECIES_HELIOLISK, SPECIES_TYRUNT, SPECIES_TYRANTRUM, SPECIES_AMAURA, SPECIES_AURORUS,
    SPECIES_SYLVEON, SPECIES_HAWLUCHA, SPECIES_DEDENNE, SPECIES_CARBINK, SPECIES_GOOMY, SPECIES_SLIGGOO,
    SPECIES_GOODRA, SPECIES_KLEFKI, SPECIES_PHANTUMP, SPECIES_TREVENANT, SPECIES_PUMPKABOO, SPECIES_GOURGEIST,
    SPECIES_BERGMITE, SPECIES_AVALUGG, SPECIES_NOIBAT, SPECIES_NOIVERN, SPECIES_XERNEAS, SPECIES_YVELTAL,
    SPECIES_ZYGARDE, SPECIES_DIANCIE, SPECIES_HOOPA, SPECIES_VOLCANION, SPECIES_ROWLET, SPECIES_DARTRIX,
    SPECIES_DECIDUEYE, SPECIES_LITTEN, SPECIES_TORRACAT, SPECIES_INCINEROAR, SPECIES_POPPLIO, SPECIES_BRIONNE,
    SPECIES_PRIMARINA, SPECIES_PIKIPEK, SPECIES_TRUMBEAK, SPECIES_TOUCANNON, SPECIES_YUNGOOS, SPECIES_GUMSHOOS,
    SPECIES_GRUBBIN, SPECIES_CHARJABUG, SPECIES_VIKAVOLT, SPECIES_CRABRAWLER, SPECIES_CRABOMINABLE, SPECIES_ORICORIO,
    SPECIES_CUTIEFLY, SPECIES_RIBOMBEE, SPECIES_ROCKRUFF, SPECIES_LYCANROC, SPECIES_WISHIWASHI, SPECIES_MAREANIE,
    SPECIES_TOXAPEX, SPECIES_MUDBRAY, SPECIES_MUDSDALE, SPECIES_DEWPIDER, SPECIES_ARAQUANID, SPECIES_FOMANTIS,
    SPECIES_LURANTIS, SPECIES_MORELULL, SPECIES_SHIINOTIC, SPECIES_SALANDIT, SPECIES_SALAZZLE, SPECIES_STUFFUL,
    SPECIES_BEWEAR, SPECIES_BOUNSWEET, SPECIES_STEENEE, SPECIES_TSAREENA, SPECIES_COMFEY, SPECIES_ORANGURU,
    SPECIES_PASSIMIAN, SPECIES_WIMPOD, SPECIES_GOLISOPOD, SPECIES_SANDYGAST, SPECIES_PALOSSAND, SPECIES_PYUKUMUKU,
    SPECIES_TYPE_NULL, SPECIES_SILVALLY, SPECIES_MINIOR, SPECIES_KOMALA, SPECIES_TURTONATOR, SPECIES_TOGEDEMARU,
    SPECIES_MIMIKYU, SPECIES_BRUXISH, SPECIES_DRAMPA, SPECIES_DHELMISE, SPECIES_JANGMO_O, SPECIES_HAKAMO_O,
    SPECIES_KOMMO_O, SPECIES_TAPU_KOKO, SPECIES_TAPU_LELE, SPECIES_TAPU_BULU, SPECIES_TAPU_FINI, SPECIES_COSMOG,
    SPECIES_COSMOEM, SPECIES_SOLGALEO, SPECIES_LUNALA, SPECIES_NIHILEGO, SPECIES_BUZZWOLE, SPECIES_PHEROMOSA,
    SPECIES_XURKITREE, SPECIES_CELESTEELA, SPECIES_KARTANA, SPECIES_GUZZLORD, SPECIES_NECROZMA, SPECIES_MAGEARNA,
    SPECIES_MARSHADOW, SPECIES_POIPOLE, SPECIES_NAGANADEL, SPECIES_STAKATAKA, SPECIES_BLACEPHALON, SPECIES_ZERAORA,
    SPECIES_MELTAN, SPECIES_MELMETAL, SPECIES_GROOKEY, SPECIES_THWACKEY, SPECIES_RILLABOOM, SPECIES_SCORBUNNY,
    SPECIES_RABOOT, SPECIES_CINDERACE, SPECIES_SOBBLE, SPECIES_DRIZZILE, SPECIES_INTELEON, SPECIES_SKWOVET,
    SPECIES_GREEDENT, SPECIES_ROOKIDEE, SPECIES_CORVISQUIRE, SPECIES_CORVIKNIGHT, SPECIES_BLIPBUG, SPECIES_DOTTLER,
    SPECIES_ORBEETLE, SPECIES_NICKIT, SPECIES_THIEVUL, SPECIES_GOSSIFLEUR, SPECIES_ELDEGOSS, SPECIES_WOOLOO,
    SPECIES_DUBWOOL, SPECIES_CHEWTLE, SPECIES_DREDNAW, SPECIES_YAMPER, SPECIES_BOLTUND, SPECIES_ROLYCOLY,
    SPECIES_CARKOL, SPECIES_COALOSSAL, SPECIES_APPLIN, SPECIES_FLAPPLE, SPECIES_APPLETUN, SPECIES_SILICOBRA,
    SPECIES_SANDACONDA, SPECIES_CRAMORANT, SPECIES_ARROKUDA, SPECIES_BARRASKEWDA, SPECIES_TOXEL, SPECIES_TOXTRICITY,
    SPECIES_SIZZLIPEDE, SPECIES_CENTISKORCH, SPECIES_CLOBBOPUS, SPECIES_GRAPPLOCT, SPECIES_SINISTEA, SPECIES_POLTEAGEIST,
    SPECIES_HATENNA, SPECIES_HATTREM, SPECIES_HATTERENE, SPECIES_IMPIDIMP, SPECIES_MORGREM, SPECIES_GRIMMSNARL,
    SPECIES_OBSTAGOON, SPECIES_PERRSERKER, SPECIES_CURSOLA, SPECIES_SIRFETCHD, SPECIES_MR_RIME, SPECIES_RUNERIGUS,
    SPECIES_MILCERY, SPECIES_ALCREMIE, SPECIES_FALINKS, SPECIES_PINCURCHIN, SPECIES_SNOM, SPECIES_FROSMOTH,
    SPECIES_STONJOURNER, SPECIES_EISCUE, SPECIES_INDEEDEE, SPECIES_MORPEKO, SPECIES_CUFANT, SPECIES_COPPERAJAH,
    SPECIES_DRACOZOLT, SPECIES_ARCTOZOLT, SPECIES_DRACOVISH, SPECIES_ARCTOVISH, SPECIES_DURALUDON, SPECIES_DREEPY,
    SPECIES_DRAKLOAK, SPECIES_DRAGAPULT, SPECIES_ZACIAN, SPECIES_ZAMAZENTA, SPECIES_ETERNATUS, SPECIES_KUBFU,
    SPECIES_URSHIFU, SPECIES_ZARUDE, SPECIES_REGIELEKI, SPECIES_REGIDRAGO, SPECIES_GLASTRIER, SPECIES_SPECTRIER,
    SPECIES_CALYREX, SPECIES_WYRDEER, SPECIES_KLEAVOR, SPECIES_URSALUNA, SPECIES_BASCULEGION, SPECIES_SNEASLER,
    SPECIES_OVERQWIL, SPECIES_ENAMORUS, SPECIES_SPRIGATITO, SPECIES_FLORAGATO, SPECIES_MEOWSCARADA, SPECIES_FUECOCO,
    SPECIES_CROCALOR, SPECIES_SKELEDIRGE, SPECIES_QUAXLY, SPECIES_QUAXWELL, SPECIES_QUAQUAVAL, SPECIES_LECHONK,
    SPECIES_OINKOLOGNE, SPECIES_TAROUNTULA, SPECIES_SPIDOPS, SPECIES_NYMBLE, SPECIES_LOKIX, SPECIES_PAWMI,
    SPECIES_PAWMO, SPECIES_PAWMOT, SPECIES_TANDEMAUS, SPECIES_MAUSHOLD, SPECIES_FIDOUGH, SPECIES_DACHSBUN,
    SPECIES_SMOLIV, SPECIES_DOLLIV, SPECIES_ARBOLIVA, SPECIES_SQUAWKABILLY, SPECIES_NACLI, SPECIES_NACLSTACK,
    SPECIES_GARGANACL, SPECIES_CHARCADET, SPECIES_ARMAROUGE, SPECIES_CERULEDGE, SPECIES_TADBULB, SPECIES_BELLIBOLT,
    SPECIES_WATTREL, SPECIES_KILOWATTREL, SPECIES_MASCHIFF, SPECIES_MABOSSTIFF, SPECIES_SHROODLE, SPECIES_GRAFAIAI,
    SPECIES_BRAMBLIN, SPECIES_BRAMBLEGHAST, SPECIES_TOEDSCOOL, SPECIES_TOEDSCRUEL, SPECIES_KLAWF, SPECIES_CAPSAKID,
    SPECIES_SCOVILLAIN, SPECIES_RELLOR, SPECIES_RABSCA, SPECIES_FLITTLE, SPECIES_ESPATHRA, SPECIES_TINKATINK,
    SPECIES_TINKATUFF, SPECIES_TINKATON, SPECIES_WIGLETT, SPECIES_WUGTRIO, SPECIES_BOMBIRDIER, SPECIES_FINIZEN,
    SPECIES_PALAFIN, SPECIES_VAROOM, SPECIES_REVAVROOM, SPECIES_CYCLIZAR, SPECIES_ORTHWORM, SPECIES_GLIMMET,
    SPECIES_GLIMMORA, SPECIES_GREAVARD, SPECIES_HOUNDSTONE, SPECIES_FLAMIGO, SPECIES_CETODDLE, SPECIES_CETITAN,
    SPECIES_VELUZA, SPECIES_DONDOZO, SPECIES_TATSUGIRI, SPECIES_ANNIHILAPE, SPECIES_CLODSIRE, SPECIES_FARIGIRAF,
    SPECIES_DUDUNSPARCE, SPECIES_KINGAMBIT, SPECIES_GREAT_TUSK, SPECIES_SCREAM_TAIL, SPECIES_BRUTE_BONNET, SPECIES_FLUTTER_MANE,
    SPECIES_SLITHER_WING, SPECIES_SANDY_SHOCKS, SPECIES_IRON_TREADS, SPECIES_IRON_BUNDLE, SPECIES_IRON_HANDS, SPECIES_IRON_JUGULIS,
    SPECIES_IRON_MOTH, SPECIES_IRON_THORNS, SPECIES_FRIGIBAX, SPECIES_ARCTIBAX, SPECIES_BAXCALIBUR, SPECIES_GIMMIGHOUL,
    SPECIES_GHOLDENGO, SPECIES_WO_CHIEN, SPECIES_CHIEN_PAO, SPECIES_TING_LU, SPECIES_CHI_YU, SPECIES_ROARING_MOON,
    SPECIES_IRON_VALIANT, SPECIES_KORAIDON, SPECIES_MIRAIDON, SPECIES_WALKING_WAKE, SPECIES_IRON_LEAVES, SPECIES_DIPPLIN,
    SPECIES_POLTCHAGEIST, SPECIES_SINISTCHA, SPECIES_OKIDOGI, SPECIES_MUNKIDORI, SPECIES_FEZANDIPITI, SPECIES_OGERPON,
    SPECIES_ARCHALUDON, SPECIES_HYDRAPPLE, SPECIES_GOUGING_FIRE, SPECIES_RAGING_BOLT, SPECIES_IRON_BOULDER, SPECIES_IRON_CROWN,
    SPECIES_TERAPAGOS, SPECIES_PECHARUNT,
};

#define WILD_RANDOMIZER_SPECIES_POOL_COUNT (sizeof(sWildRandomizerSpeciesPool) / sizeof(sWildRandomizerSpeciesPool[0]))

// simple, fast integer hash (murmur3-style finalizer) - we don't need cryptographic quality,
// just a good spread so that nearby seeds/species/levels don't map to nearby pool indices.
static u32 WildRandomizer_Hash(u32 x)
{
    x ^= x >> 16;
    x *= 0x7feb352du;
    x ^= x >> 15;
    x *= 0x846ca68bu;
    x ^= x >> 16;
    return x;
}

u32 LONG_CALL WildEncounterRandomizer_GetOrCreateSeed(void)
{
#ifdef ALLOW_SAVE_CHANGES
    struct SAVE_MISC_DATA *saveMiscData = Sav2_Misc_get(SaveBlock2_get());
    u32 seed;

    if (!saveMiscData->wildRandomizerSeedSet) {
        seed = ((u32)gf_rand() << 16) | (u32)gf_rand();
        if (seed == 0) {
            seed = 1; // 0 is reserved to mean "not generated yet", never use it as a real seed
        }
        saveMiscData->wildRandomizerSeed = seed;
        saveMiscData->wildRandomizerSeedSet = 1;
    }

    seed = saveMiscData->wildRandomizerSeed;

    return seed;
#else
    return 0;
#endif
}

u16 LONG_CALL WildEncounterRandomizer_GetReplacementSpecies(u16 originalSpecies, u8 level)
{
    if (originalSpecies == SPECIES_NONE || WILD_RANDOMIZER_SPECIES_POOL_COUNT == 0) {
        return originalSpecies;
    }

#ifdef ALLOW_SAVE_CHANGES
    u32 seed = WildEncounterRandomizer_GetOrCreateSeed();
    // Fold the player's current map into the hash too, not just species+level - otherwise two
    // different routes that happen to share the exact same vanilla (species, level) slot
    // (extremely common for early-game mons like Rattata/Pidgey/Sentret, which vanilla repeats
    // across many routes at similar levels) would always get handed the exact same substitute
    // on every route that has it, making the whole game feel far less varied than the per-route
    // encounter tables actually allow for. PlayerLocationHistoryGetBack reads the same
    // save-tracked "where the player currently/most recently was" data the roamers already use
    // to avoid the player's location, so this stays fully deterministic per save (the same route
    // always gives the same mon on a replay) while letting each route draw its own slice of the
    // pool instead of sharing one with every other route that has an overlapping vanilla slot.
    void *roamerSave = EncDataSave_GetSaveDataPtr(SaveBlock2_get());
    u32 mapId = PlayerLocationHistoryGetBack(roamerSave);
    u32 mixed = WildRandomizer_Hash(seed ^ ((u32)originalSpecies << 16) ^ ((u32)level << 8) ^ (mapId * 0x2545F491u) ^ 0x9E3779B9u);
    u32 index = mixed % WILD_RANDOMIZER_SPECIES_POOL_COUNT;

    return sWildRandomizerSpeciesPool[index];
#else
    return originalSpecies;
#endif
}

// -----------------------------------------------------------------------------------------
// Trainer randomizer. Reuses the exact same per-save seed, hash and species pool as the wild
// encounter randomizer above, so it needs no seed of its own. Gym leaders, the Elite Four and
// the Champion are always excluded, no matter what, so a run still ends with a fair, vanilla
// boss fight even though every rank-and-file trainer (route trainers, gym grunts, the rival,
// Team Rocket, etc.) can have a randomized team.
//
// This can't check the trainer's class at runtime: data/Trainers.c's sTrainerData array only
// exists on the PC, read by tools/trainerdatagen to build the trainer narcs baked into the
// ROM - it is never linked into the game itself, so referencing it here fails at link time.
// Instead this is a fixed list of trainer IDs (the same numbers as data/Trainers.c's own
// [N] = { ... } indices, which is exactly what ends up in bp->trainer_id[num] at runtime)
// for every entry whose .trainerClass is a gym leader, an Elite Four member or the Champion.
// Regenerate this list from data/Trainers.c (grep for trainerClass = TRAINERCLASS_LEADER_*/
// _CHAMPION/_ELITE_FOUR_* and note each match's [N] index) if trainers are added, removed,
// reordered, or a rematch/postgame version of a boss fight is added.
static const u16 sTrainerRandomizerExcludedIds[] = {
    20, 21, 30, 31, 32, 33, 34, 35, // Falkner, Bugsy, Whitney, Morty, Pryce, Jasmine, Chuck, Clair
    244, 245, 246, 247, // Champion, Elite Four (Will, Karen, Koga)
    253, 254, 255, 256, 257, 258, 259, 261, // Brock, Misty, Lt. Surge, Erika, Janine, Sabrina, Blaine, Blue
    418, // Elite Four (Bruno)
    701, 702, 703, 704, 705, // rematch: Champion, Elite Four (Will, Koga, Bruno, Karen)
    712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, // rematch: all 16 gym leaders
    733, 734, // rematch: Champion, Clair (again)
};
#define TRAINER_RANDOMIZER_EXCLUDED_ID_COUNT (sizeof(sTrainerRandomizerExcludedIds) / sizeof(sTrainerRandomizerExcludedIds[0]))

static BOOL TrainerRandomizer_IsExcludedId(u32 trainerId)
{
    u32 i;

    for (i = 0; i < TRAINER_RANDOMIZER_EXCLUDED_ID_COUNT; i++) {
        if (sTrainerRandomizerExcludedIds[i] == trainerId) {
            return TRUE;
        }
    }

    return FALSE;
}

u16 LONG_CALL TrainerRandomizer_GetReplacementSpecies(u32 trainerId, u8 partySlot, u16 originalSpecies, u8 level)
{
    if (originalSpecies == SPECIES_NONE || WILD_RANDOMIZER_SPECIES_POOL_COUNT == 0) {
        return originalSpecies;
    }

    if (TrainerRandomizer_IsExcludedId(trainerId)) {
        return originalSpecies;
    }

#ifdef ALLOW_SAVE_CHANGES
    u32 seed = WildEncounterRandomizer_GetOrCreateSeed();
    // trainer + party slot mixed in (and a different constant than the wild-encounter hash)
    // so this doesn't line up with wild encounters, and so two Pokemon on the same trainer's
    // team don't collide with each other even when they share a species/level.
    u32 mixed = WildRandomizer_Hash(seed ^ (trainerId * 0x2545F491u) ^ ((u32)partySlot << 24) ^ ((u32)originalSpecies << 16) ^ ((u32)level << 8) ^ 0x27D4EB2Fu);
    u32 index = mixed % WILD_RANDOMIZER_SPECIES_POOL_COUNT;

    return sWildRandomizerSpeciesPool[index];
#else
    return originalSpecies;
#endif
}

// -----------------------------------------------------------------------------------------
// Starter randomizer. Kept as 3 separate, same-typed pools (rather than reusing the wild
// encounter pool above) so slot 0 always stays grass, slot 1 always stays fire and slot 2
// always stays water - that keeps the classic type triangle (and the rival's fixed,
// type-advantaged answer in data/Trainers.c, which this feature does not touch) intact even
// though the actual species differs from the vanilla Chikorita/Cyndaquil/Totodile line.
static const u16 sStarterPoolGrass[] = {
    SPECIES_BULBASAUR, SPECIES_IVYSAUR, SPECIES_VENUSAUR,
    SPECIES_CHIKORITA, SPECIES_BAYLEEF, SPECIES_MEGANIUM,
    SPECIES_TREECKO, SPECIES_GROVYLE, SPECIES_SCEPTILE,
    SPECIES_TURTWIG, SPECIES_GROTLE, SPECIES_TORTERRA,
    SPECIES_SNIVY, SPECIES_SERVINE, SPECIES_SERPERIOR,
    SPECIES_CHESPIN, SPECIES_QUILLADIN, SPECIES_CHESNAUGHT,
    SPECIES_ROWLET, SPECIES_DARTRIX, SPECIES_DECIDUEYE,
    SPECIES_GROOKEY, SPECIES_THWACKEY, SPECIES_RILLABOOM,
    SPECIES_SPRIGATITO, SPECIES_FLORAGATO, SPECIES_MEOWSCARADA,
};
#define STARTER_POOL_GRASS_COUNT (sizeof(sStarterPoolGrass) / sizeof(sStarterPoolGrass[0]))

static const u16 sStarterPoolFire[] = {
    SPECIES_CHARMANDER, SPECIES_CHARMELEON, SPECIES_CHARIZARD,
    SPECIES_CYNDAQUIL, SPECIES_QUILAVA, SPECIES_TYPHLOSION,
    SPECIES_TORCHIC, SPECIES_COMBUSKEN, SPECIES_BLAZIKEN,
    SPECIES_CHIMCHAR, SPECIES_MONFERNO, SPECIES_INFERNAPE,
    SPECIES_TEPIG, SPECIES_PIGNITE, SPECIES_EMBOAR,
    SPECIES_FENNEKIN, SPECIES_BRAIXEN, SPECIES_DELPHOX,
    SPECIES_LITTEN, SPECIES_TORRACAT, SPECIES_INCINEROAR,
    SPECIES_SCORBUNNY, SPECIES_RABOOT, SPECIES_CINDERACE,
    SPECIES_FUECOCO, SPECIES_CROCALOR, SPECIES_SKELEDIRGE,
};
#define STARTER_POOL_FIRE_COUNT (sizeof(sStarterPoolFire) / sizeof(sStarterPoolFire[0]))

static const u16 sStarterPoolWater[] = {
    SPECIES_SQUIRTLE, SPECIES_WARTORTLE, SPECIES_BLASTOISE,
    SPECIES_TOTODILE, SPECIES_CROCONAW, SPECIES_FERALIGATR,
    SPECIES_MUDKIP, SPECIES_MARSHTOMP, SPECIES_SWAMPERT,
    SPECIES_PIPLUP, SPECIES_PRINPLUP, SPECIES_EMPOLEON,
    SPECIES_OSHAWOTT, SPECIES_DEWOTT, SPECIES_SAMUROTT,
    SPECIES_FROAKIE, SPECIES_FROGADIER, SPECIES_GRENINJA,
    SPECIES_POPPLIO, SPECIES_BRIONNE, SPECIES_PRIMARINA,
    SPECIES_SOBBLE, SPECIES_DRIZZILE, SPECIES_INTELEON,
    SPECIES_QUAXLY, SPECIES_QUAXWELL, SPECIES_QUAQUAVAL,
};
#define STARTER_POOL_WATER_COUNT (sizeof(sStarterPoolWater) / sizeof(sStarterPoolWater[0]))

u16 LONG_CALL StarterRandomizer_GetReplacementSpecies(u8 slot)
{
    const u16 *pool;
    u32 poolCount;

    switch (slot) {
    case 0:
        pool = sStarterPoolGrass;
        poolCount = STARTER_POOL_GRASS_COUNT;
        break;
    case 1:
        pool = sStarterPoolFire;
        poolCount = STARTER_POOL_FIRE_COUNT;
        break;
    case 2:
        pool = sStarterPoolWater;
        poolCount = STARTER_POOL_WATER_COUNT;
        break;
    default:
        return SPECIES_NONE;
    }

#ifdef ALLOW_SAVE_CHANGES
    {
        u32 seed = WildEncounterRandomizer_GetOrCreateSeed();
        // different constant than the wild-encounter hash so the two features don't line up
        u32 mixed = WildRandomizer_Hash(seed ^ ((u32)slot << 24) ^ 0x27D4EB2Fu);
        u32 index = mixed % poolCount;

        return pool[index];
    }
#else
    return pool[0];
#endif
}

// -----------------------------------------------------------------------------------------
// Item randomizers.
//
// sHiddenItemPool backs every hidden item (the ones found with the Itemfinder). It used to be
// just the ~48 distinct items vanilla already hands out through this system - which meant a
// hidden item could only ever turn into another equally mundane consumable (and could even
// reroll back to itself). It's now every item ID 1-1000 that isn't a key item, a TM/HM, an
// unnamed/unused "ITEM_UNKNOWN_*" slot, or anything Z-move related (Z-Crystals, the Z-Ring/
// Z-Power Ring - Z-moves are disabled in this hack, see config.h) - so Mega Stones and the
// curated competitive-item set (Leftovers, Choice items, Eviolite, ...) can turn up here too,
// same pool the ground-item-ball randomizer draws from (see _080A in
// armips/scr_seq/scr_seq_00003_commonscript.s) and the Mega Stone/competitive item shops draw
// from (MegaStoneShop_GetItems / CompetitiveItemShop_GetItems below).
static const u16 sHiddenItemPool[] = {
    ITEM_MASTER_BALL, ITEM_ULTRA_BALL, ITEM_GREAT_BALL, ITEM_POKE_BALL, ITEM_SAFARI_BALL, ITEM_NET_BALL,
    ITEM_DIVE_BALL, ITEM_NEST_BALL, ITEM_REPEAT_BALL, ITEM_TIMER_BALL, ITEM_LUXURY_BALL, ITEM_PREMIER_BALL,
    ITEM_DUSK_BALL, ITEM_HEAL_BALL, ITEM_QUICK_BALL, ITEM_CHERISH_BALL, ITEM_POTION, ITEM_ANTIDOTE,
    ITEM_BURN_HEAL, ITEM_ICE_HEAL, ITEM_AWAKENING, ITEM_PARALYZE_HEAL, ITEM_FULL_RESTORE, ITEM_MAX_POTION,
    ITEM_HYPER_POTION, ITEM_SUPER_POTION, ITEM_FULL_HEAL, ITEM_REVIVE, ITEM_MAX_REVIVE, ITEM_FRESH_WATER,
    ITEM_SODA_POP, ITEM_LEMONADE, ITEM_MOOMOO_MILK, ITEM_ENERGY_POWDER, ITEM_ENERGY_ROOT, ITEM_HEAL_POWDER,
    ITEM_REVIVAL_HERB, ITEM_ETHER, ITEM_MAX_ETHER, ITEM_ELIXIR, ITEM_MAX_ELIXIR, ITEM_LAVA_COOKIE,
    ITEM_BERRY_JUICE, ITEM_SACRED_ASH, ITEM_HP_UP, ITEM_PROTEIN, ITEM_IRON, ITEM_CARBOS,
    ITEM_CALCIUM, ITEM_RARE_CANDY, ITEM_PP_UP, ITEM_ZINC, ITEM_PP_MAX, ITEM_OLD_GATEAU,
    ITEM_GUARD_SPEC, ITEM_DIRE_HIT, ITEM_X_ATTACK, ITEM_X_DEFENSE, ITEM_X_SPEED, ITEM_X_ACCURACY,
    ITEM_X_SP_ATK, ITEM_X_SP_DEF, ITEM_POKE_DOLL, ITEM_FLUFFY_TAIL, ITEM_BLUE_FLUTE, ITEM_YELLOW_FLUTE,
    ITEM_RED_FLUTE, ITEM_BLACK_FLUTE, ITEM_WHITE_FLUTE, ITEM_SHOAL_SALT, ITEM_SHOAL_SHELL, ITEM_RED_SHARD,
    ITEM_BLUE_SHARD, ITEM_YELLOW_SHARD, ITEM_GREEN_SHARD, ITEM_SUPER_REPEL, ITEM_MAX_REPEL, ITEM_ESCAPE_ROPE,
    ITEM_REPEL, ITEM_SUN_STONE, ITEM_MOON_STONE, ITEM_FIRE_STONE, ITEM_THUNDER_STONE, ITEM_WATER_STONE,
    ITEM_LEAF_STONE, ITEM_TINY_MUSHROOM, ITEM_BIG_MUSHROOM, ITEM_PEARL, ITEM_BIG_PEARL, ITEM_STARDUST,
    ITEM_STAR_PIECE, ITEM_NUGGET, ITEM_HEART_SCALE, ITEM_HONEY, ITEM_GROWTH_MULCH, ITEM_DAMP_MULCH,
    ITEM_STABLE_MULCH, ITEM_GOOEY_MULCH, ITEM_ROOT_FOSSIL, ITEM_CLAW_FOSSIL, ITEM_HELIX_FOSSIL, ITEM_DOME_FOSSIL,
    ITEM_OLD_AMBER, ITEM_ARMOR_FOSSIL, ITEM_SKULL_FOSSIL, ITEM_RARE_BONE, ITEM_SHINY_STONE, ITEM_DUSK_STONE,
    ITEM_DAWN_STONE, ITEM_OVAL_STONE, ITEM_ODD_KEYSTONE, ITEM_GRISEOUS_ORB, ITEM_DOUSE_DRIVE, ITEM_SHOCK_DRIVE,
    ITEM_BURN_DRIVE, ITEM_CHILL_DRIVE, ITEM_POKEMON_BOX, ITEM_SWEET_HEART, ITEM_ADAMANT_ORB, ITEM_LUSTROUS_ORB,
    ITEM_GRASS_MAIL, ITEM_FLAME_MAIL, ITEM_BUBBLE_MAIL, ITEM_BLOOM_MAIL, ITEM_TUNNEL_MAIL, ITEM_STEEL_MAIL,
    ITEM_HEART_MAIL, ITEM_SNOW_MAIL, ITEM_SPACE_MAIL, ITEM_AIR_MAIL, ITEM_MOSAIC_MAIL, ITEM_BRICK_MAIL,
    ITEM_CHERI_BERRY, ITEM_CHESTO_BERRY, ITEM_PECHA_BERRY, ITEM_RAWST_BERRY, ITEM_ASPEAR_BERRY, ITEM_LEPPA_BERRY,
    ITEM_ORAN_BERRY, ITEM_PERSIM_BERRY, ITEM_LUM_BERRY, ITEM_SITRUS_BERRY, ITEM_FIGY_BERRY, ITEM_WIKI_BERRY,
    ITEM_MAGO_BERRY, ITEM_AGUAV_BERRY, ITEM_IAPAPA_BERRY, ITEM_RAZZ_BERRY, ITEM_BLUK_BERRY, ITEM_NANAB_BERRY,
    ITEM_WEPEAR_BERRY, ITEM_PINAP_BERRY, ITEM_POMEG_BERRY, ITEM_KELPSY_BERRY, ITEM_QUALOT_BERRY, ITEM_HONDEW_BERRY,
    ITEM_GREPA_BERRY, ITEM_TAMATO_BERRY, ITEM_CORNN_BERRY, ITEM_MAGOST_BERRY, ITEM_RABUTA_BERRY, ITEM_NOMEL_BERRY,
    ITEM_SPELON_BERRY, ITEM_PAMTRE_BERRY, ITEM_WATMEL_BERRY, ITEM_DURIN_BERRY, ITEM_BELUE_BERRY, ITEM_OCCA_BERRY,
    ITEM_PASSHO_BERRY, ITEM_WACAN_BERRY, ITEM_RINDO_BERRY, ITEM_YACHE_BERRY, ITEM_CHOPLE_BERRY, ITEM_KEBIA_BERRY,
    ITEM_SHUCA_BERRY, ITEM_COBA_BERRY, ITEM_PAYAPA_BERRY, ITEM_TANGA_BERRY, ITEM_CHARTI_BERRY, ITEM_KASIB_BERRY,
    ITEM_HABAN_BERRY, ITEM_COLBUR_BERRY, ITEM_BABIRI_BERRY, ITEM_CHILAN_BERRY, ITEM_LIECHI_BERRY, ITEM_GANLON_BERRY,
    ITEM_SALAC_BERRY, ITEM_PETAYA_BERRY, ITEM_APICOT_BERRY, ITEM_LANSAT_BERRY, ITEM_STARF_BERRY, ITEM_ENIGMA_BERRY,
    ITEM_MICLE_BERRY, ITEM_CUSTAP_BERRY, ITEM_JABOCA_BERRY, ITEM_ROWAP_BERRY, ITEM_BRIGHT_POWDER, ITEM_WHITE_HERB,
    ITEM_MACHO_BRACE, ITEM_EXP_SHARE, ITEM_QUICK_CLAW, ITEM_SOOTHE_BELL, ITEM_MENTAL_HERB, ITEM_CHOICE_BAND,
    ITEM_KINGS_ROCK, ITEM_SILVER_POWDER, ITEM_AMULET_COIN, ITEM_CLEANSE_TAG, ITEM_SOUL_DEW, ITEM_DEEP_SEA_TOOTH,
    ITEM_DEEP_SEA_SCALE, ITEM_SMOKE_BALL, ITEM_EVERSTONE, ITEM_FOCUS_BAND, ITEM_LUCKY_EGG, ITEM_SCOPE_LENS,
    ITEM_METAL_COAT, ITEM_LEFTOVERS, ITEM_DRAGON_SCALE, ITEM_LIGHT_BALL, ITEM_SOFT_SAND, ITEM_HARD_STONE,
    ITEM_MIRACLE_SEED, ITEM_BLACK_GLASSES, ITEM_BLACK_BELT, ITEM_MAGNET, ITEM_MYSTIC_WATER, ITEM_SHARP_BEAK,
    ITEM_POISON_BARB, ITEM_NEVER_MELT_ICE, ITEM_SPELL_TAG, ITEM_TWISTED_SPOON, ITEM_CHARCOAL, ITEM_DRAGON_FANG,
    ITEM_SILK_SCARF, ITEM_UP_GRADE, ITEM_SHELL_BELL, ITEM_SEA_INCENSE, ITEM_LAX_INCENSE, ITEM_LUCKY_PUNCH,
    ITEM_METAL_POWDER, ITEM_THICK_CLUB, ITEM_LEEK, ITEM_RED_SCARF, ITEM_BLUE_SCARF, ITEM_PINK_SCARF,
    ITEM_GREEN_SCARF, ITEM_YELLOW_SCARF, ITEM_WIDE_LENS, ITEM_MUSCLE_BAND, ITEM_WISE_GLASSES, ITEM_EXPERT_BELT,
    ITEM_LIGHT_CLAY, ITEM_LIFE_ORB, ITEM_POWER_HERB, ITEM_TOXIC_ORB, ITEM_FLAME_ORB, ITEM_QUICK_POWDER,
    ITEM_FOCUS_SASH, ITEM_ZOOM_LENS, ITEM_METRONOME, ITEM_IRON_BALL, ITEM_LAGGING_TAIL, ITEM_DESTINY_KNOT,
    ITEM_BLACK_SLUDGE, ITEM_ICY_ROCK, ITEM_SMOOTH_ROCK, ITEM_HEAT_ROCK, ITEM_DAMP_ROCK, ITEM_GRIP_CLAW,
    ITEM_CHOICE_SCARF, ITEM_STICKY_BARB, ITEM_POWER_BRACER, ITEM_POWER_BELT, ITEM_POWER_LENS, ITEM_POWER_BAND,
    ITEM_POWER_ANKLET, ITEM_POWER_WEIGHT, ITEM_SHED_SHELL, ITEM_BIG_ROOT, ITEM_CHOICE_SPECS, ITEM_FLAME_PLATE,
    ITEM_SPLASH_PLATE, ITEM_ZAP_PLATE, ITEM_MEADOW_PLATE, ITEM_ICICLE_PLATE, ITEM_FIST_PLATE, ITEM_TOXIC_PLATE,
    ITEM_EARTH_PLATE, ITEM_SKY_PLATE, ITEM_MIND_PLATE, ITEM_INSECT_PLATE, ITEM_STONE_PLATE, ITEM_SPOOKY_PLATE,
    ITEM_DRACO_PLATE, ITEM_DREAD_PLATE, ITEM_IRON_PLATE, ITEM_ODD_INCENSE, ITEM_ROCK_INCENSE, ITEM_FULL_INCENSE,
    ITEM_WAVE_INCENSE, ITEM_ROSE_INCENSE, ITEM_LUCK_INCENSE, ITEM_PURE_INCENSE, ITEM_PROTECTOR, ITEM_ELECTIRIZER,
    ITEM_MAGMARIZER, ITEM_DUBIOUS_DISC, ITEM_REAPER_CLOTH, ITEM_RAZOR_CLAW, ITEM_RAZOR_FANG, ITEM_EXPLORER_KIT,
    ITEM_RED_APRICORN, ITEM_YELLOW_APRICORN, ITEM_BLUE_APRICORN, ITEM_GREEN_APRICORN, ITEM_PINK_APRICORN, ITEM_WHITE_APRICORN,
    ITEM_BLACK_APRICORN, ITEM_FAST_BALL, ITEM_LEVEL_BALL, ITEM_LURE_BALL, ITEM_HEAVY_BALL, ITEM_LOVE_BALL,
    ITEM_FRIEND_BALL, ITEM_MOON_BALL, ITEM_SPORT_BALL, ITEM_PARK_BALL, ITEM_DATA_CARD_01, ITEM_DATA_CARD_02,
    ITEM_DATA_CARD_03, ITEM_DATA_CARD_04, ITEM_DATA_CARD_05, ITEM_DATA_CARD_06, ITEM_DATA_CARD_07, ITEM_DATA_CARD_08,
    ITEM_DATA_CARD_09, ITEM_DATA_CARD_10, ITEM_DATA_CARD_11, ITEM_DATA_CARD_12, ITEM_DATA_CARD_13, ITEM_DATA_CARD_14,
    ITEM_DATA_CARD_15, ITEM_DATA_CARD_16, ITEM_DATA_CARD_17, ITEM_DATA_CARD_18, ITEM_DATA_CARD_19, ITEM_DATA_CARD_20,
    ITEM_DATA_CARD_21, ITEM_DATA_CARD_22, ITEM_DATA_CARD_23, ITEM_DATA_CARD_24, ITEM_DATA_CARD_25, ITEM_DATA_CARD_26,
    ITEM_DATA_CARD_27, ITEM_PRISM_SCALE, ITEM_EVIOLITE, ITEM_FLOAT_STONE, ITEM_ROCKY_HELMET, ITEM_AIR_BALLOON,
    ITEM_RED_CARD, ITEM_RING_TARGET, ITEM_BINDING_BAND, ITEM_ABSORB_BULB, ITEM_CELL_BATTERY, ITEM_EJECT_BUTTON,
    ITEM_FIRE_GEM, ITEM_WATER_GEM, ITEM_ELECTRIC_GEM, ITEM_GRASS_GEM, ITEM_ICE_GEM, ITEM_FIGHTING_GEM,
    ITEM_POISON_GEM, ITEM_GROUND_GEM, ITEM_FLYING_GEM, ITEM_PSYCHIC_GEM, ITEM_BUG_GEM, ITEM_ROCK_GEM,
    ITEM_GHOST_GEM, ITEM_DRAGON_GEM, ITEM_DARK_GEM, ITEM_STEEL_GEM, ITEM_NORMAL_GEM, ITEM_HEALTH_FEATHER,
    ITEM_MUSCLE_FEATHER, ITEM_RESIST_FEATHER, ITEM_GENIUS_FEATHER, ITEM_CLEVER_FEATHER, ITEM_SWIFT_FEATHER, ITEM_PRETTY_FEATHER,
    ITEM_COVER_FOSSIL, ITEM_PLUME_FOSSIL, ITEM_LIBERTY_PASS, ITEM_PASS_ORB, ITEM_DREAM_BALL, ITEM_POKE_TOY,
    ITEM_PROP_CASE, ITEM_DRAGON_SKULL, ITEM_BALM_MUSHROOM, ITEM_BIG_NUGGET, ITEM_PEARL_STRING, ITEM_COMET_SHARD,
    ITEM_RELIC_COPPER, ITEM_RELIC_SILVER, ITEM_RELIC_GOLD, ITEM_RELIC_VASE, ITEM_RELIC_BAND, ITEM_RELIC_STATUE,
    ITEM_RELIC_CROWN, ITEM_CASTELIACONE, ITEM_DIRE_HIT_2, ITEM_X_SPEED_2, ITEM_X_SP_ATK_2, ITEM_X_SP_DEF_2,
    ITEM_X_DEFENSE_2, ITEM_X_ATTACK_2, ITEM_X_ACCURACY_2, ITEM_X_SPEED_3, ITEM_X_SP_ATK_3, ITEM_X_SP_DEF_3,
    ITEM_X_DEFENSE_3, ITEM_X_ATTACK_3, ITEM_X_ACCURACY_3, ITEM_X_SPEED_6, ITEM_X_SP_ATK_6, ITEM_X_SP_DEF_6,
    ITEM_X_DEFENSE_6, ITEM_X_ATTACK_6, ITEM_X_ACCURACY_6, ITEM_ABILITY_URGE, ITEM_ITEM_DROP, ITEM_ITEM_URGE,
    ITEM_RESET_URGE, ITEM_DIRE_HIT_3, ITEM_XTRANSCEIVER_BW, ITEM_GRAM_1, ITEM_GRAM_2, ITEM_GRAM_3,
    ITEM_XTRANSCEIVER_BW2, ITEM_MEDAL_BOX, ITEM_DNA_SPLICERS_UNFUSE, ITEM_PERMIT, ITEM_PLASMA_CARD, ITEM_GRUBBY_HANKY,
    ITEM_COLRESS_MACHINE, ITEM_DROPPED_ITEM_CURTIS, ITEM_DROPPED_ITEM_YANCY, ITEM_WEAKNESS_POLICY, ITEM_ASSAULT_VEST, ITEM_HOLO_CASTER_MALE,
    ITEM_PROFS_LETTER, ITEM_ROLLER_SKATES, ITEM_PIXIE_PLATE, ITEM_ABILITY_CAPSULE, ITEM_WHIPPED_DREAM, ITEM_SACHET,
    ITEM_LUMINOUS_MOSS, ITEM_SNOWBALL, ITEM_SAFETY_GOGGLES, ITEM_POKE_FLUTE, ITEM_RICH_MULCH, ITEM_SURPRISE_MULCH,
    ITEM_BOOST_MULCH, ITEM_AMAZE_MULCH, ITEM_GENGARITE, ITEM_GARDEVOIRITE, ITEM_AMPHAROSITE, ITEM_VENUSAURITE,
    ITEM_CHARIZARDITE_X, ITEM_BLASTOISINITE, ITEM_MEWTWONITE_X, ITEM_MEWTWONITE_Y, ITEM_BLAZIKENITE, ITEM_MEDICHAMITE,
    ITEM_HOUNDOOMINITE, ITEM_AGGRONITE, ITEM_BANETTITE, ITEM_TYRANITARITE, ITEM_SCIZORITE, ITEM_PINSIRITE,
    ITEM_AERODACTYLITE, ITEM_LUCARIONITE, ITEM_ABOMASITE, ITEM_KANGASKHANITE, ITEM_GYARADOSITE, ITEM_ABSOLITE,
    ITEM_CHARIZARDITE_Y, ITEM_ALAKAZITE, ITEM_HERACRONITE, ITEM_MAWILITE, ITEM_MANECTITE, ITEM_GARCHOMPITE,
    ITEM_LATIASITE, ITEM_LATIOSITE, ITEM_ROSELI_BERRY, ITEM_KEE_BERRY, ITEM_MARANGA_BERRY, ITEM_SPRINKLOTAD,
    ITEM_POWER_PLANT_PASS, ITEM_INTRIGUING_STONE, ITEM_COMMON_STONE, ITEM_DISCOUNT_COUPON, ITEM_ELEVATOR_KEY, ITEM_TMV_PASS,
    ITEM_HONOR_OF_KALOS, ITEM_ADVENTURE_GUIDE, ITEM_STRANGE_SOUVENIR, ITEM_LENS_CASE, ITEM_MAKEUP_BAG, ITEM_TRAVEL_TRUNK,
    ITEM_LUMIOSE_GALETTE, ITEM_SHALOUR_SABLE, ITEM_JAW_FOSSIL, ITEM_SAIL_FOSSIL, ITEM_LOOKER_TICKET, ITEM_BIKE_XY,
    ITEM_HOLO_CASTER_FEMALE, ITEM_FAIRY_GEM, ITEM_MEGA_CHARM, ITEM_MEGA_GLOVE, ITEM_MACH_BIKE, ITEM_ACRO_BIKE,
    ITEM_WAILMER_PAIL, ITEM_DEVON_PARTS, ITEM_SOOT_SACK, ITEM_BASEMENT_KEY_ORAS, ITEM_POKEBLOCK_KIT, ITEM_LETTER,
    ITEM_EON_TICKET, ITEM_SCANNER, ITEM_GO_GOGGLES, ITEM_METEORITE_ORAS_DEFAULT, ITEM_KEY_TO_ROOM_1, ITEM_KEY_TO_ROOM_2,
    ITEM_KEY_TO_ROOM_4, ITEM_KEY_TO_ROOM_6, ITEM_STORAGE_KEY_HOENN, ITEM_DEVON_SCOPE, ITEM_SS_TICKET_ORAS, ITEM_DEVON_SCUBA_GEAR,
    ITEM_CONTEST_COSTUME_MALE, ITEM_CONTEST_COSTUME_FEMALE, ITEM_MAGMA_SUIT, ITEM_AQUA_SUIT, ITEM_PAIR_OF_TICKETS, ITEM_MEGA_BRACELET,
    ITEM_MEGA_PENDANT, ITEM_MEGA_GLASSES, ITEM_MEGA_ANCHOR, ITEM_MEGA_STICKPIN, ITEM_MEGA_TIARA, ITEM_MEGA_ANKLET,
    ITEM_METEORITE_ORAS_SECOND, ITEM_SWAMPERTITE, ITEM_SCEPTILITE, ITEM_SABLENITE, ITEM_ALTARIANITE, ITEM_GALLADITE,
    ITEM_AUDINITE, ITEM_METAGROSSITE, ITEM_SHARPEDONITE, ITEM_SLOWBRONITE, ITEM_STEELIXITE, ITEM_PIDGEOTITE,
    ITEM_GLALITITE, ITEM_DIANCITE, ITEM_MEGA_CUFF, ITEM_CAMERUPTITE, ITEM_LOPUNNITE, ITEM_SALAMENCITE,
    ITEM_BEEDRILLITE, ITEM_METEORITE_ORAS_THIRD, ITEM_METEORITE_ORAS_FINAL, ITEM_METEORITE_SHARD, ITEM_EON_FLUTE, ITEM_BOTTLE_CAP,
    ITEM_GOLD_BOTTLE_CAP, ITEM_FORAGE_BAG, ITEM_FISHING_ROD_SM, ITEM_PROFESSORS_MASK, ITEM_FESTIVAL_TICKET, ITEM_SPARKLING_STONE,
    ITEM_ADRENALINE_ORB, ITEM_ICE_STONE, ITEM_RIDE_PAGER, ITEM_BEAST_BALL, ITEM_BIG_MALASADA, ITEM_RED_NECTAR,
    ITEM_YELLOW_NECTAR, ITEM_PINK_NECTAR, ITEM_PURPLE_NECTAR, ITEM_ENIGMATIC_CARD, ITEM_SILVER_RAZZ_BERRY, ITEM_GOLDEN_RAZZ_BERRY,
    ITEM_SILVER_NANAB_BERRY, ITEM_GOLDEN_NANAB_BERRY, ITEM_SILVER_PINAP_BERRY, ITEM_GOLDEN_PINAP_BERRY, ITEM_SECRET_KEY_LGPE, ITEM_SS_TICKET_LGPE,
    ITEM_PARCEL_LGPE, ITEM_CARD_KEY_KANTO, ITEM_TERRAIN_EXTENDER, ITEM_PROTECTIVE_PADS, ITEM_ELECTRIC_SEED, ITEM_PSYCHIC_SEED,
    ITEM_MISTY_SEED, ITEM_GRASSY_SEED, ITEM_STRETCHY_SPRING, ITEM_CHALKY_STONE, ITEM_MARBLE, ITEM_LONE_EARRING,
    ITEM_BEACH_GLASS, ITEM_GOLD_LEAF, ITEM_SILVER_LEAF, ITEM_POLISHED_MUD_BALL, ITEM_TROPICAL_SHELL, ITEM_LEAF_LETTER_1,
    ITEM_LEAF_LETTER_2, ITEM_SMALL_BOUQUET, ITEM_LURE, ITEM_SUPER_LURE, ITEM_MAX_LURE, ITEM_PEWTER_CRUNCHIES,
    ITEM_FIGHTING_MEMORY, ITEM_FLYING_MEMORY, ITEM_POISON_MEMORY, ITEM_GROUND_MEMORY, ITEM_ROCK_MEMORY, ITEM_BUG_MEMORY,
    ITEM_GHOST_MEMORY, ITEM_STEEL_MEMORY, ITEM_FIRE_MEMORY, ITEM_WATER_MEMORY, ITEM_GRASS_MEMORY, ITEM_ELECTRIC_MEMORY,
    ITEM_PSYCHIC_MEMORY, ITEM_ICE_MEMORY, ITEM_DRAGON_MEMORY, ITEM_DARK_MEMORY, ITEM_FAIRY_MEMORY, ITEM_PINK_PETAL,
    ITEM_ORANGE_PETAL, ITEM_BLUE_PETAL, ITEM_RED_PETAL, ITEM_GREEN_PETAL, ITEM_YELLOW_PETAL, ITEM_PURPLE_PETAL,
    ITEM_RAINBOW_FLOWER, ITEM_SURGE_BADGE, ITEM_N_SOLARIZER_UNFUSE, ITEM_N_LUNARIZER_UNFUSE, ITEM_LEFT_POKE_BALL, ITEM_ROTO_HATCH,
    ITEM_ROTO_BARGAIN, ITEM_ROTO_PRIZE_MONEY, ITEM_ROTO_EXP_POINTS, ITEM_ROTO_FRIENDSHIP, ITEM_ROTO_ENCOUNTER, ITEM_ROTO_STEALTH,
    ITEM_ROTO_HP_RESTORE, ITEM_ROTO_PP_RESTORE, ITEM_ROTO_BOOST, ITEM_ROTO_CATCH, ITEM_HEALTH_CANDY, ITEM_MIGHTY_CANDY,
    ITEM_TOUGH_CANDY, ITEM_SMART_CANDY, ITEM_COURAGE_CANDY, ITEM_QUICK_CANDY, ITEM_HEALTH_CANDY_L, ITEM_MIGHTY_CANDY_L,
    ITEM_TOUGH_CANDY_L, ITEM_SMART_CANDY_L, ITEM_COURAGE_CANDY_L, ITEM_QUICK_CANDY_L, ITEM_HEALTH_CANDY_XL, ITEM_MIGHTY_CANDY_XL,
    ITEM_TOUGH_CANDY_XL, ITEM_SMART_CANDY_XL, ITEM_COURAGE_CANDY_XL, ITEM_QUICK_CANDY_XL, ITEM_BULBASAUR_CANDY, ITEM_CHARMANDER_CANDY,
    ITEM_SQUIRTLE_CANDY, ITEM_CATERPIE_CANDY, ITEM_WEEDLE_CANDY, ITEM_PIDGEY_CANDY, ITEM_RATTATA_CANDY, ITEM_SPEAROW_CANDY,
    ITEM_EKANS_CANDY, ITEM_PIKACHU_CANDY, ITEM_SANDSHREW_CANDY, ITEM_NIDORAN_FEMALE_CANDY, ITEM_NIDORAN_MALE_CANDY, ITEM_CLEFAIRY_CANDY,
    ITEM_VULPIX_CANDY, ITEM_JIGGLYPUFF_CANDY, ITEM_ZUBAT_CANDY, ITEM_ODDISH_CANDY, ITEM_PARAS_CANDY, ITEM_VENONAT_CANDY,
    ITEM_DIGLETT_CANDY, ITEM_MEOWTH_CANDY, ITEM_PSYDUCK_CANDY,
};
#define HIDDEN_ITEM_POOL_COUNT (sizeof(sHiddenItemPool) / sizeof(sHiddenItemPool[0]))

// sRockSmashItemPool is unchanged: exactly the distinct items vanilla already hands out through
// the Rock Smash reward tables - nothing here is a key item, TM, or anything that could block
// progression, since the vanilla designers already vetted every one of these as a fine,
// disposable pickup.
static const u16 sRockSmashItemPool[] = {
    ITEM_BIG_PEARL, ITEM_BLUE_SHARD, ITEM_CLAW_FOSSIL, ITEM_GREEN_SHARD, ITEM_HEART_SCALE,
    ITEM_HELIX_FOSSIL, ITEM_MAX_ETHER, ITEM_MAX_REVIVE, ITEM_OLD_AMBER, ITEM_PEARL, ITEM_RARE_BONE,
    ITEM_RED_SHARD, ITEM_REVIVE, ITEM_STAR_PIECE, ITEM_YELLOW_SHARD,
};
#define ROCK_SMASH_ITEM_POOL_COUNT (sizeof(sRockSmashItemPool) / sizeof(sRockSmashItemPool[0]))

u16 LONG_CALL ItemRandomizer_GetReplacementHiddenItem(u16 originalItem, u16 locationIndex)
{
    if (originalItem == ITEM_NONE) {
        return originalItem;
    }

#ifdef ALLOW_SAVE_CHANGES
    {
        u32 seed = WildEncounterRandomizer_GetOrCreateSeed();
        u32 mixed = WildRandomizer_Hash(seed ^ ((u32)locationIndex << 16) ^ 0x1B873593u);
        u32 index = mixed % HIDDEN_ITEM_POOL_COUNT;

        return sHiddenItemPool[index];
    }
#else
    return originalItem;
#endif
}

u16 LONG_CALL ItemRandomizer_GetReplacementRockSmashItem(u16 originalItem, u32 tableIndex, u32 quality)
{
    if (originalItem == ITEM_NONE) {
        return originalItem;
    }

#ifdef ALLOW_SAVE_CHANGES
    {
        u32 seed = WildEncounterRandomizer_GetOrCreateSeed();
        u32 mixed = WildRandomizer_Hash(seed ^ ((tableIndex & 0xFFu) << 20) ^ ((quality & 0xFFu) << 12) ^ 0x85EBCA6Bu);
        u32 index = mixed % ROCK_SMASH_ITEM_POOL_COUNT;

        return sRockSmashItemPool[index];
    }
#else
    return originalItem;
#endif
}

// -----------------------------------------------------------------------------------------
// Shared helper for "offer a random subset of a shop's full item pool" features (Mega Stone
// shop, competitive item shop, ...). Shuffles (only) the first numToPick slots of pool into a
// deterministic-per-save order (a partial Fisher-Yates shuffle) and copies them to outItems.
// saltXor should be a constant unique to the calling feature, so two features drawing from
// the same seed don't end up correlated with each other.
static u32 RandomSubset_Pick(u16 *pool, u32 poolCount, u16 *outItems, u32 maxOut, u32 saltXor)
{
    u32 numToPick = maxOut;
    u32 i;

    if (numToPick > poolCount) {
        numToPick = poolCount;
    }

#ifdef ALLOW_SAVE_CHANGES
    {
        u32 seed = WildEncounterRandomizer_GetOrCreateSeed();

        // partial Fisher-Yates shuffle, seeded deterministically per save - only shuffles as
        // many slots as we actually need (numToPick), not the whole pool.
        for (i = 0; i < numToPick; i++) {
            u32 mixed = WildRandomizer_Hash(seed ^ (i << 16) ^ saltXor);
            u32 j = i + (mixed % (poolCount - i));
            u16 tmp = pool[i];
            pool[i] = pool[j];
            pool[j] = tmp;
        }
    }
#endif

    for (i = 0; i < numToPick; i++) {
        outItems[i] = pool[i];
    }

    return numToPick;
}

// -----------------------------------------------------------------------------------------
// Mega Stone shop pool. Every Mega Stone in the game: the official Gen 6 set plus every
// custom stone this hack adds on top (same ranges as the existing IS_ITEM_MEGA_STONE macro
// in include/constants/item.h - keep the two in sync if new Mega Stones are ever added).
#define MEGA_STONE_POOL_CAPACITY 128

static u32 BuildMegaStonePool(u16 *outPool, u32 capacity)
{
    u32 count = 0;
    u32 item;

    for (item = ITEM_GENGARITE; item <= ITEM_LATIOSITE && count < capacity; item++) {
        outPool[count++] = (u16)item;
    }
    for (item = ITEM_SWAMPERTITE; item <= ITEM_DIANCITE && count < capacity; item++) {
        outPool[count++] = (u16)item;
    }
    for (item = ITEM_CAMERUPTITE; item <= ITEM_BEEDRILLITE && count < capacity; item++) {
        outPool[count++] = (u16)item;
    }
    for (item = ITEM_CLEFABLITE; item <= ITEM_FALINKSITE && count < capacity; item++) {
        outPool[count++] = (u16)item;
    }
    for (item = ITEM_RAICHUNITE_X; item <= ITEM_GLIMMORANITE && count < capacity; item++) {
        outPool[count++] = (u16)item;
    }

    return count;
}

u32 LONG_CALL MegaStoneShop_GetItems(u16 *outItems, u32 maxOut)
{
    u16 pool[MEGA_STONE_POOL_CAPACITY];
    u32 poolCount = BuildMegaStonePool(pool, MEGA_STONE_POOL_CAPACITY);

#ifdef MEGA_STONE_SHOP_MAX_ITEMS
    if (maxOut > MEGA_STONE_SHOP_MAX_ITEMS) {
        maxOut = MEGA_STONE_SHOP_MAX_ITEMS;
    }
#endif

    return RandomSubset_Pick(pool, poolCount, outItems, maxOut, 0x2545F491u);
}

// -----------------------------------------------------------------------------------------
// Competitive item shop pool. A curated list of held items useful in competitive play - none
// of these are key items, TMs, or anything that could block progression.
static const u16 sCompetitiveItemPool[] = {
    ITEM_LEFTOVERS, ITEM_LIFE_ORB, ITEM_CHOICE_BAND, ITEM_CHOICE_SPECS, ITEM_CHOICE_SCARF,
    ITEM_FOCUS_SASH, ITEM_ASSAULT_VEST, ITEM_ROCKY_HELMET, ITEM_EVIOLITE, ITEM_BLACK_SLUDGE,
    ITEM_EXPERT_BELT, ITEM_AIR_BALLOON, ITEM_SAFETY_GOGGLES, ITEM_WEAKNESS_POLICY, ITEM_WIDE_LENS,
    ITEM_MUSCLE_BAND, ITEM_WISE_GLASSES, ITEM_SCOPE_LENS, ITEM_KINGS_ROCK, ITEM_SHELL_BELL,
    ITEM_LIGHT_CLAY, ITEM_MENTAL_HERB, ITEM_HEAVY_DUTY_BOOTS, ITEM_GRIP_CLAW, ITEM_LOADED_DICE,
    ITEM_CLEAR_AMULET, ITEM_COVERT_CLOAK, ITEM_PUNCHING_GLOVE, ITEM_MIRROR_HERB, ITEM_ABILITY_SHIELD,
    ITEM_BOOSTER_ENERGY, ITEM_THROAT_SPRAY, ITEM_ROOM_SERVICE, ITEM_BLUNDER_POLICY, ITEM_UTILITY_UMBRELLA,
    ITEM_ADRENALINE_ORB, ITEM_TERRAIN_EXTENDER,
};
#define COMPETITIVE_ITEM_POOL_COUNT (sizeof(sCompetitiveItemPool) / sizeof(sCompetitiveItemPool[0]))

u32 LONG_CALL CompetitiveItemShop_GetItems(u16 *outItems, u32 maxOut)
{
    u16 pool[COMPETITIVE_ITEM_POOL_COUNT];
    u32 i;

    for (i = 0; i < COMPETITIVE_ITEM_POOL_COUNT; i++) {
        pool[i] = sCompetitiveItemPool[i];
    }

#ifdef COMPETITIVE_ITEM_SHOP_MAX_ITEMS
    if (maxOut > COMPETITIVE_ITEM_SHOP_MAX_ITEMS) {
        maxOut = COMPETITIVE_ITEM_SHOP_MAX_ITEMS;
    }
#endif

    // different salt than the Mega Stone shop so the two random picks don't line up
    return RandomSubset_Pick(pool, COMPETITIVE_ITEM_POOL_COUNT, outItems, maxOut, 0x9E3779B1u);
}

// -----------------------------------------------------------------------------------------
// Second-clerk town shops. Several towns' Poke Mart has a second clerk next to the main
// badge-gated one (src/field/mart.c's ScrCmd_MartBuy), selling a couple of Mail types and a
// themed Poke Ball for that town (e.g. Violet City: Tunnel Mail + Heal/Net Ball) - previously
// a small fixed list per town, now a per-save random draw from a shared pool a peticion, so
// this shop varies between playthroughs too, same as the wild Pokemon. Every "collector" Poke
// Ball a Johto/Kanto-era shop could plausibly sell (Poke/Great/Ultra/Master are excluded -
// those stay tied to badge count via sBadgeMartFixed - as are Safari/Cherish/Dream/Beast/Sport/
// Park Ball and every later-gen ball past Moon Ball, none of which fit here) plus every Mail
// type (IS_ITEM_MAIL's full range) make up the pool.
#define SECOND_CLERK_POOL_CAPACITY 32

static u32 BuildSecondClerkPool(u16 *outPool, u32 capacity)
{
    u32 count = 0;
    u32 item;

    for (item = ITEM_NET_BALL; item <= ITEM_QUICK_BALL && count < capacity; item++) {
        outPool[count++] = (u16)item;
    }
    for (item = ITEM_FAST_BALL; item <= ITEM_MOON_BALL && count < capacity; item++) {
        outPool[count++] = (u16)item;
    }
    for (item = ITEM_GRASS_MAIL; item <= ITEM_BRICK_MAIL && count < capacity; item++) {
        outPool[count++] = (u16)item;
    }

    return count;
}

u32 LONG_CALL SecondClerkShop_GetItems(u16 *outItems, u32 maxOut, u32 townSalt)
{
    u16 pool[SECOND_CLERK_POOL_CAPACITY];
    u32 poolCount = BuildSecondClerkPool(pool, SECOND_CLERK_POOL_CAPACITY);

    // townSalt (a small constant unique to each town) keeps every town's draw independent
    // from the others, even though they all share this same pool and save seed.
    return RandomSubset_Pick(pool, poolCount, outItems, maxOut, 0x53434C4Bu ^ townSalt); // "SCLK" base salt
}
